Alexandria/src/Alexandria/Controllers/GamesController.cs
using Alexandria.Data;
using Alexandria.Models;
using Data.Repositories;
using libatalex.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading;
using System.Xml;

namespace Alexandria.Controllers
{
    [RequireHttps]
    public class GamesController : Controller
    {
        private readonly ApplicationDbContext db;

        public GamesController(ApplicationDbContext _db)
        {
            db = _db;
        }
        // GET: Games
        public ActionResult Index()
        {
            //UpdateGameInfo();
            //db.Games.Where(g=>g.Owners.Any(o=>o.UserId == User))
            var userManager = HttpContext.RequestServices.GetService(typeof(UserManager<ApplicationUser>)) as UserManager<ApplicationUser>;
            var userId = userManager.GetUserId(User);
            return View(db.Games.Where(g => g.Owners.Any(o => o.UserId == userId)).ToList());
        }

        private void UpdateGameInfo()
        {
            var games = db.Games.ToList().OrderBy(g => g.Title);
            foreach (var game in games)
            {
                game.Title = game.Title.Trim();
                db.SaveChanges();

                if (game.MaxPlayers != 0)
                {
                    continue;
                }
                var objectId = GetObjectId(game.Title);
                if (objectId != null)
                {
                    var values = GetDetails(objectId);
                    game.MinimumAgeYears = int.Parse(values["age"]);
                    game.MaxPlayers = int.Parse(values["maxplayers"]);
                    game.PlayTimeMinutes = int.Parse(values["playingtime"]);
                    game.MinPlayers = int.Parse(values["minplayers"]);
                    db.SaveChanges();
                    Thread.Sleep(1000);
                }
            }
        }

        private string GetObjectId(string name)
        {
            var searchURI = "http://www.boardgamegeek.com/xmlapi/search";

            string uriSuffix = ("?search=[GAMENAME]").Replace("[GAMENAME]", name.Trim(' '));
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(searchURI);
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/xml"));

            byte[] dataObjects = null;
            client.GetByteArrayAsync(uriSuffix).ContinueWith(task =>
            {
                var foo = name;
                dataObjects = task.Result;
            }).Wait();
            string xmlResponse = System.Text.Encoding.UTF8.GetString(dataObjects);

            XmlDocument xmlDoc = new XmlDocument();
            xmlDoc.LoadXml(xmlResponse);
            var element = xmlDoc.GetElementsByTagName("boardgame")[0];
            if (element != null)
            {
                var objectId = element.Attributes["objectid"];
                return objectId.Value;
            }
            return null;
        }

        private Dictionary<string, string> GetDetails(string objectId)
        {
            var gameURI = "http://www.boardgamegeek.com/xmlapi/boardgame/[GAMEID]";

            string completeUri = gameURI.Replace("[GAMEID]", objectId);
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(completeUri);
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/xml"));

            byte[] dataObjects = null;
            client.GetByteArrayAsync("").ContinueWith(task =>
            {
                var foo = objectId;
                dataObjects = task.Result;
            }).Wait();
            string xmlResponse = System.Text.Encoding.UTF8.GetString(dataObjects);

            XmlDocument xmlDoc = new XmlDocument();
            xmlDoc.LoadXml(xmlResponse);
            var element = xmlDoc.GetElementsByTagName("minplayers")[0];
            var minplayers = element.InnerText;
            element = xmlDoc.GetElementsByTagName("maxplayers")[0];
            var maxplayers = element.InnerText;
            element = xmlDoc.GetElementsByTagName("playingtime")[0];
            var playingtime = element.InnerText;
            element = xmlDoc.GetElementsByTagName("age")[0];
            var age = element.InnerText;
            var res = new Dictionary<string, string>();
            res.Add("minplayers", minplayers);
            res.Add("maxplayers", maxplayers);
            res.Add("playingtime", playingtime);
            res.Add("age", age);
            return res;
        }

        // GET: Games/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Game game = db.Games.FirstOrDefault(g => g.Id == id);
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }

        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Game game)
        {
            if (ModelState.IsValid)
            {
                return Redirect("Index");
            }
            return View(game);
        }
        // GET: Games/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(include: "Id,Title,NumberOfPlayers,PlayTimeMinutes,MinimumAgeYears,IsOnShelf")] Game game)
        {
            if (ModelState.IsValid)
            {
                game.Id = Guid.NewGuid();
                db.Games.Add(game);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(game);
        }

        // GET: Games/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Game game = db.Games.FirstOrDefault(g => g.Id == id);
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(include: "Id,Title,NumberOfPlayers,PlayTimeMinutes,MinimumAgeYears,IsOnShelf")] Game game)
        {
            if (ModelState.IsValid)
            {
                db.Entry(game).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(game);
        }

        // GET: Games/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Game game = db.Games.FirstOrDefault(g => g.Id == id);
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Game game = db.Games.FirstOrDefault(g => g.Id == id);
            db.Games.Remove(game);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Play(Guid id)
        {
            using (var repo = new GameRepo())
            {
                if (repo.Play(id))
                {
                    return PartialView("_PlaySuccess");
                }
                else
                {
                    return PartialView("_PlayFailure");
                }
            }
        }

        [HttpPost]
        public ActionResult CheckIn(Guid id)
        {
            using (var repo = new GameRepo())
            {
                if (repo.CheckIn(id))
                {
                    return PartialView("_CheckInSuccess");
                }
                else
                {
                    return PartialView("_CheckInFailure");
                }
            }
        }

        public ActionResult Lend(Guid id)
        {
            var vm = new LendViewModel();
            vm.GameId = id;
            return PartialView("_Lend", vm);
        }

        [HttpPost]
        public ActionResult Lend(LendViewModel vm)
        {
            using (var repo = new GameRepo())
            {
                repo.LendOut(vm.GameId, vm.BorrowerName);
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Alexandria/src/Alexandria/Views/Games/Add.cshtml
@model Alexandria.Data.Game

@{
    ViewBag.Title = "Add a game to your collection";
}

<h2>Add a game to your collection</h2>

<div class="input-group">
    <span class="input-group-btn">
        <button class="btn btn-default" type="button">Go!</button>
    </span>
    <input id="gameSearch" type="text" class="form-control" placeholder="Enter a game title...">
</div>

<div id="searchResults"></div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Alexandria/src/Alexandria/Views/Games/Create.cshtml
@model Alexandria.Data.Game

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Game</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinPlayers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinPlayers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinPlayers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxPlayers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxPlayers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxPlayers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlayTimeMinutes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlayTimeMinutes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlayTimeMinutes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinimumAgeYears, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinimumAgeYears, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinimumAgeYears, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsOnShelf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsOnShelf)
                    @Html.ValidationMessageFor(model => model.IsOnShelf, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Alexandria/src/Alexandria/Views/Games/Delete.cshtml
@model Data.Models.Game

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Game</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinPlayers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinPlayers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxPlayers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxPlayers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlayTimeMinutes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlayTimeMinutes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinimumAgeYears)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinimumAgeYears)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsOnShelf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsOnShelf)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Alexandria/src/Alexandria/Views/Games/Details.cshtml
@model Data.Models.Game

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Game</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinPlayers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinPlayers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxPlayers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxPlayers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlayTimeMinutes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlayTimeMinutes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinimumAgeYears)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinimumAgeYears)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsOnShelf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsOnShelf)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Alexandria/src/Alexandria/Views/Games/Edit.cshtml
@model Data.Models.Game

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Game</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinPlayers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinPlayers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinPlayers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxPlayers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxPlayers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxPlayers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlayTimeMinutes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlayTimeMinutes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlayTimeMinutes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinimumAgeYears, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinimumAgeYears, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinimumAgeYears, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsOnShelf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsOnShelf)
                    @Html.ValidationMessageFor(model => model.IsOnShelf, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Alexandria/src/Alexandria/Views/Games/Index.cshtml
@model IEnumerable<Alexandria.Data.Game>

@{
    ViewBag.Title = "Index";
    var buttonClass = "btn btn-primary";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    @Html.ActionLink("Add Game", "Add")
</p>
<table id="gamesTable" class="table table-condensed responsive table-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MinPlayers)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxPlayers)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlayTimeMinutes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MinimumAgeYears)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var cssClass = item.IsOnShelf ? "" : "danger";
            <tr class="@(cssClass)">
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MinPlayers)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxPlayers)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlayTimeMinutes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MinimumAgeYears)
                </td>
                <td>
                    <div class="btn-toolbar" role="toolbar" aria-label="...">
                        @if (item.IsOnShelf)
                        {
                            <a asp-action="Play" asp-controller="Games" asp-route-area="Global" asp-route-id="@item.Id"
                               data-ajax="true" data-ajax-method="Post" data-ajax-mode="replace" data-ajax-update="#alertHolder" title="Play"
                               class="glyphicon glyphicon-play @(buttonClass)"/>

                            <a asp-action="Lend" asp-controller="Games" asp-route-area="Global" asp-route-id="@item.Id"
                               data-ajax="true" data-ajax-method="Post" data-ajax-mode="replace" data-ajax-update="#alertHolder" title="Lend"
                               class="glyphicon glyphicon-gift  @(buttonClass)"/>
                        }
                        else
                        {
                            <a asp-action="Result" asp-controller="Games" asp-route-area="Global" asp-route-id="@item.Id"
                               data-ajax="true" data-ajax-method="Post" data-ajax-mode="replace" data-ajax-update="#alertHolder" title="Log Result"
                               class="glyphicon glyphicon-record  @(buttonClass)"/>

                            <a asp-action="CheckIn" asp-controller="Games" asp-route-area="Global" asp-route-id="@item.Id"
                               data-ajax="true" data-ajax-method="Post" data-ajax-mode="replace" data-ajax-update="#alertHolder" title="Check In"
                               class="glyphicon glyphicon-step-backward  @(buttonClass)"/>
                        }

                        @Html.ActionLink("", "Edit", new { id = item.Id }, new { @class = $"{buttonClass} glyphicon-pencil glyphicon", title="Edit" })
                        @Html.ActionLink("", "Details", new { id = item.Id }, new { @class = $"{buttonClass} glyphicon glyphicon-list", title="View Details" })
                        @Html.ActionLink("", "Delete", new { id = item.Id }, new { @class = $"{buttonClass} glyphicon glyphicon-trash", title="Delete From Collection" })

                    </div>
                </td>
            </tr>
                   }
    </tbody>
</table>